# ASD Services Configuration
# This file contains all the services displayed in the ASD dashboard
# Format: YAML for better readability and maintainability
# Source: https://github.com/spencerjirehcebrian/asd

# Dashboard Configuration
title: 'ASD'

services:
  # Deployment & Infrastructure
  - id: coolify
    name: Coolify
    description: Self-hosted application deployment platform and Heroku alternative
    url: https://coolify.spencerjireh.com
    category: deployment
    # Self-hosted Heroku alternative for application deployment

  # Productivity & Notes
  - id: memos
    name: Memos
    description: Self-hosted memo and note-taking service
    url: https://memos.spencerjireh.com
    category: productivity
    # Personal memo and note-taking platform

  # Development & Code Management
  - id: weavyr
    name: Weavyr
    description: Code collection service
    url: https://weavyr.spencerjireh.com
    category: development
    # Code snippet and collection management

  # Personal & Portfolio
  - id: portfolio
    name: Portfolio
    description: Personal portfolio and showcase website
    url: https://cebrian.spencerjireh.com
    category: personal
    # Personal portfolio and showcase website

  # Dashboard & Feed
  - id: glance
    name: Glance
    description: Self-hosted feed and homepage service
    url: https://glance.spencerjireh.com
    category: dashboard
    # Self-hosted homepage and feed aggregator

  # Monitoring & Performance
  - id: glances
    name: Glances
    description: System monitoring and performance dashboard
    url: https://glances.spencerjireh.com
    category: monitoring
    # System performance and resource monitoring

  # Documentation & Wiki
  - id: docmost
    name: Docmost
    description: Self-hosted documentation and wiki platform
    url: https://docmost.spencerjireh.com
    category: documentation
    # Self-hosted documentation and knowledge base

  # AI & Machine Learning
  - id: ollama/open-webui
    name: Ollama/Open-WebUI
    description: Web interface for running local large language models
    url: https://ollama.spencerjireh.com
    category: ai
    # Local LLM hosting and web interface

  # Utilities & Tools
  - id: stirling-pdf
    name: Stirling-PDF
    description: Web-based PDF manipulation and processing tool
    url: https://pdf.spencerjireh.com
    category: utilities
    # PDF processing and manipulation tools

  - id: convertx
    name: ConvertX
    description: File format conversion service
    url: https://convertx.spencerjireh.com
    category: utilities
    # Multi-format file conversion service

  # Database Management
  - id: cloudbeaver
    name: CloudBeaver
    description: Web-based SQL database management
    url: https://cloudbeaver.spencerjireh.com
    category: database
    # Web-based database administration tool
